kind: Pod
apiVersion: v1
metadata:
  name: mysql-env-pod
spec:
  containers:
  - name: mysql-container
    image: mysql
    ports:
    - containerPort: 3306
      protocol: TCP
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"
      