# kubectl run web --image=nginx:latest --port=80
apiVersion: v1
kind: Pod 
metadata:
  name: web 
  namespace: testbed-ns
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
    