kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deploy
spec:
  replicas: 3
  selector:
   matchLabels:
     app: webui
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
      - name: web
        image: nginx:1.14
        ports:
        - containerPort: 80
