kind: Deployment
apiVersion: apps/v1
metadata:
  name: app-deploy
  annotations:
    kubernetes.io/change-cause: version 1.15 # --record 옵션
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 10
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 3
  selector:
   matchLabels:
     app: webui
  template:
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
      - name: web
        image: nginx:1.15
        ports:
        - containerPort: 80
