apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sts-nginx
spec:
  replicas: 3
  serviceName: sts-service
# podManagementPolicy: OrderedReady  # default value
# https://kubernetes.io/ko/docs/concepts/workloads/controllers/statefulset/#파드-관리-정책
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: mysts
  template:
    metadata:
      name: nginx-pod
      labels:
        app: mysts
    spec:
      containers:
      - name: sts-container
        image: nginx:1.14
        ports:
        - containerPort: 80
    